SNOW_USER=DBT_APP
SNOW_PASSWORD=dbtPassword123
SNOW_ACCOUNT=znetmyd-cf85683   # e.g. abc12345.ap-south-1
SNOW_WAREHOUSE=DBT_DEMO
SNOW_DATABASE=DB_DEMO_DBT
SNOW_SCHEMA=PUBLIC
SNOWFLAKE_ROLE=DBT_APP_ROLE

